### ISSUE TITLE
Running the kafka-using quickstart examples results in an error

### ISSUE THREAD

**Issue by benissimo** [pinot-contrib/pinot-docs#148] opened 2023-02-18 20:27 UTC
When I try running

```
docker run \
    -p 9000:9000 \
    apachepinot/pinot:0.9.3 QuickStart \
    -type stream
```

or

```
docker run \
    -p 9000:9000 \
    apachepinot/pinot:0.9.3 QuickStart \
    -type stream_json_index
```

I get this error:

```
***** Starting Kafka *****
***** Starting meetup data stream and publishing to Kafka *****
javax.websocket.DeploymentException: Handshake error.
...
Caused by: org.glassfish.tyrus.core.HandshakeException: Response code was not 101: 404.
	at org.glassfish.tyrus.client.TyrusClientEngine.processResponse(TyrusClientEngine.java:299)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleHandshake(GrizzlyClientFilter.java:322)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:291)
```

The other quickstart examples, those not containing kafka, run without error.
Is there some step I'm missing? Do these quickstart examples assume I already have Kafka running?

**Comment by matthewhelmke** [comment] 2023-03-31 19:17
I tested both of these using the latest release and could not reproduce the error. If you are able, please try again using `pinot:0.12.1` or `pinot:latest` and comment again here with the results. Thank you!

**Comment by matthewhelmke** [comment] 2023-05-15 16:32
As this is old and I couldn't reproduce with newer releases, I'm going to close the issue.

**Closed as completed by matthewhelmke** 2023-05-15 16:32 UTC
